### ISSUE TITLE
Showing the word

### ISSUE THREAD

**Issue by VulcanWM** [JBYT27/PogRater#3]
This isn't really a problem but I think it'd be way better if it showed the word in the output as right now it just shows the score.
eg.
![Screenshot 2021-11-09 at 18.33.17](https://storage.googleapis.com/replit/images/1636482805211_98c96363d6b4f988e1791f1b5ae766b1.png)
also this was when I entered JBYT27

**Comment by JBYT27** [comment]
Ah, okay. Thanks for the suggestion, I'll try that ASAP!

> LOL

**Comment by VulcanWM** [comment]
Nice! Tell me when you add it
Also the none error is back lmao

**Comment by JBYT27** [comment]
Oh lmao, ill fix it ASAp lmfao

thanks for letting me know again!

**Comment by VulcanWM** [comment]
damn error still here
also can I suggest smth?
instead of saving all the stuff like emojis and score with cookies why don’t you render the template with the variables which you can show in the template with {{var_name}}

**Comment by JBYT27** [comment]
Hmmm, I'll take a look at it again.
Well, how would I get the info then? I can't transfer the info from a route to another without cookies (i think)

**Comment by JBYT27** [comment]
Hey @VulcanWM, it seems to work for me, if you take a look at it here below:
![Screenshot 2021-11-10 7 45 50 AM](https://user-images.githubusercontent.com/76911308/141115467-9b476ee6-f9fd-4452-88f8-77e08cfb7c2e.png)

Could you take a screenshot of the error?
> I also tried deleting all the cookies and rerunning because there were so much cookies, maybe it'll work now?

**Comment by VulcanWM** [comment]
It works for me now!
If you want, I could show you an example of how to do it

**Comment by JBYT27** [comment]
Oh okay!
Oh, sure, if you want lol

**Comment by VulcanWM** [comment]
This is what I mean: https://replit.com/@VulcanWM/jbyt27-test

**Comment by JBYT27** [comment]
TYSM!!

**Comment by VulcanWM** [comment]
np! did it help?

**Comment by JBYT27** [comment]
Yeahh, I'll prob use it later :DD

**Comment by VulcanWM** [comment]
nice :)

**Comment by VulcanWM** [comment]
Also shouldn’t we close this issue lmao?

**Comment by JBYT27** [comment]
Haha, yeah, prob should xD 

I'll close it rn

**Comment by VulcanWM** [comment]
cool ;)
